# Configuration for RedShield AI
# SME Optimized: Includes road network, model hyperparameters, and updated assets.
data:
  # Coordinates are specified as [latitude, longitude]
  hospitals:
    "Hospital General": { location: [32.5295, -117.0182], capacity: 100, load: 85 }
    "IMSS Clínica 1": { location: [32.5121, -117.0145], capacity: 120, load: 70 }
    "Angeles": { location: [32.5300, -117.0200], capacity: 100, load: 95 }
    "Cruz Roja Tijuana": { location: [32.5283, -117.0255], capacity: 70, load: 60 } # Geocoded to Alfonso Gamboa
  ambulances:
    "A01": { location: [32.515, -117.04], status: "Available" }
    "A02": { location: [32.535, -116.96], status: "Available" }
    "A03": { location: [32.52, -117.12], status: "On Mission" }
    "A04": { location: [32.525, -117.02], status: "Available" }
    "A05": { location: [32.515, -117.115], status: "Available" }
    "A06": { location: [32.538, -116.97], status: "Available" }
    "A07": { location: [32.50, -117.03], status: "Available" }
    "A08": { location: [32.531, -117.015], status: "Available" }
    "A09": { location: [32.51, -116.98], status: "Available" }
  zones:
    "Zona Río": { polygon: [[32.52, -117.01], [32.53, -117.01], [32.53, -117.03], [32.52, -117.03]], crime: 0.7, road_quality: 0.9 }
    "Otay": { polygon: [[32.53, -116.95], [32.54, -116.95], [32.54, -116.98], [32.53, -116.98]], crime: 0.5, road_quality: 0.7 }
    "Playas": { polygon: [[32.51, -117.11], [32.53, -117.11], [32.53, -117.13], [32.51, -117.13]], crime: 0.4, road_quality: 0.8 }
  patient_vitals:
    "P001": { heart_rate: 145, oxygen: 88, ambulance: "A03" }
    "P002": { heart_rate: 90, oxygen: 97, ambulance: "A01" }
    "P003": { heart_rate: 150, oxygen: 99, ambulance: "A02" }
  road_network:
    nodes:
      "N_ZR1": { pos: [32.525, -117.02] }
      "N_ZR2": { pos: [32.528, -117.01] }
      "N_OT1": { pos: [32.535, -116.965] }
      "N_PL1": { pos: [32.52, -117.12] }
      "N_H_Gen": { pos: [32.5295, -117.0182] }
      "N_H_IMSS": { pos: [32.5121, -117.0145] }
      "N_H_Ang": { pos: [32.5300, -117.0200] }
      "N_H_CruzR": { pos: [32.5283, -117.0255] }
      "N_Amb_A01": { pos: [32.515, -117.04] }
    edges:
      - ["N_ZR1", "N_ZR2", 2.5]
      - ["N_ZR1", "N_H_Ang", 0.5]
      - ["N_ZR1", "N_H_CruzR", 0.7]
      - ["N_ZR2", "N_H_Gen", 0.8]
      - ["N_ZR2", "N_H_IMSS", 3.0]
      - ["N_ZR1", "N_Amb_A01", 4.0]
      - ["N_ZR1", "N_PL1", 8.0]
      - ["N_ZR2", "N_OT1", 9.0]
      - ["N_PL1", "N_Amb_A01", 5.0]
      - ["N_OT1", "N_H_IMSS", 6.0]
  model_params:
    n_estimators: 250
    max_depth: 5
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8

styling:
  colors: {available: [0, 179, 89, 255], on_mission: [150, 150, 150, 180], hospital_ok: [0, 179, 89], hospital_warn: [255, 191, 0], hospital_crit: [220, 53, 69], incident_halo: [220, 53, 69], route_path: [0, 123, 255]}
  sizes: {ambulance_available: 4.5, ambulance_mission: 2.5, hospital: 4.0, incident_base: 5.0}
  icons: {hospital: "https://img.icons8.com/color/96/hospital-3.png", ambulance: "https://img.icons8.com/color/96/ambulance.png"}
