# Configuration for RedShield AI
# SME Optimized: Includes road network, model hyperparameters, and lat/lon coordinate format.
data:
  # Coordinates are specified as [latitude, longitude]
  hospitals:
    "Hospital General": { location: [32.5295, -117.0182], capacity: 100, load: 85 }
    "IMSS Clínica 1": { location: [32.5121, -117.0145], capacity: 120, load: 70 }
    "Angeles": { location: [32.5300, -117.0200], capacity: 100, load: 95 }
  ambulances:
    "A01": { location: [32.515, -117.04], status: "Available" }
    "A02": { location: [32.535, -116.96], status: "Available" }
    "A03": { location: [32.52, -117.12], status: "On Mission" }
  zones:
    "Zona Río": { polygon: [[32.52, -117.01], [32.53, -117.01], [32.53, -117.03], [32.52, -117.03]], crime: 0.7, road_quality: 0.9 }
    "Otay": { polygon: [[32.53, -116.95], [32.54, -116.95], [32.54, -116.98], [32.53, -116.98]], crime: 0.5, road_quality: 0.7 }
    "Playas": { polygon: [[32.51, -117.11], [32.53, -117.11], [32.53, -117.13], [32.51, -117.13]], crime: 0.4, road_quality: 0.8 }
  patient_vitals:
    "P001": { heart_rate: 145, oxygen: 88, ambulance: "A03" }
    "P002": { heart_rate: 90, oxygen: 97, ambulance: "A01" }
    "P003": { heart_rate: 150, oxygen: 99, ambulance: "A02" }

  # NEW: City Road Network Graph for A* Routing
  road_network:
    nodes: # Key intersections and points of interest
      "N_ZR1": { pos: [32.525, -117.02] } # Zona Rio Center
      "N_ZR2": { pos: [32.528, -117.01] } # Zona Rio East
      "N_OT1": { pos: [32.535, -116.965] } # Otay Center
      "N_PL1": { pos: [32.52, -117.12] } # Playas Center
      "N_H_Gen": { pos: [32.5295, -117.0182] }
      "N_H_IMSS": { pos: [32.5121, -117.0145] }
      "N_H_Ang": { pos: [32.5300, -117.0200] }
      "N_Amb_A01": { pos: [32.515, -117.04] }
    edges: # Connections between nodes: [node1, node2, base_travel_time]
      - ["N_ZR1", "N_ZR2", 2.5]
      - ["N_ZR1", "N_H_Ang", 0.5]
      - ["N_ZR2", "N_H_Gen", 0.8]
      - ["N_ZR2", "N_H_IMSS", 3.0]
      - ["N_ZR1", "N_Amb_A01", 4.0]
      - ["N_ZR1", "N_PL1", 8.0]
      - ["N_ZR2", "N_OT1", 9.0]
      - ["N_PL1", "N_Amb_A01", 5.0]
      - ["N_OT1", "N_H_IMSS", 6.0]

  # NEW: XGBoost Model Hyperparameters (allows tuning without code changes)
  model_params:
    n_estimators: 250
    max_depth: 5
    learning_rate: 0.05
    subsample: 0.8
    colsample_bytree: 0.8

styling:
  colors: {available: [0, 179, 89, 255], on_mission: [150, 150, 150, 180], hospital_ok: [0, 179, 89], hospital_warn: [255, 191, 0], hospital_crit: [220, 53, 69], incident_halo: [220, 53, 69], route_path: [0, 123, 255]}
  sizes: {ambulance_available: 4.5, ambulance_mission: 2.5, hospital: 4.0, incident_base: 5.0}
  icons: {hospital: "https://img.icons8.com/color/96/hospital-3.png", ambulance: "https://img.icons8.com/color/96/ambulance.png"}
